# Generated by Django 3.1.3 on 2020-11-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0002_auto_20201104_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
