# Generated by Django 3.1.3 on 2020-11-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201105_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='address',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='evaluation',
        ),
    ]
