# Generated by Django 3.1.3 on 2020-12-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_touristspot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='touristspots'),
        ),
    ]
