# Generated by Django 3.1.3 on 2020-11-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='aproved',
            field=models.BooleanField(default=True),
        ),
    ]
